import base64

import numpy as np
import pytest

import mojo_openctm as ctm
from mojo_openctm._lib import addr, lib
from mojo_openctm.codec import _grid, _index_deltas, _sorted_triangles


# Generated by unmodified OpenCTM 1.0.3 ctmSave at compression level 1.
UPSTREAM_MG1 = (
    "T0NUTQUAAABNRzEABgAAAAUAAAABAAAAAQAAAAEAAAAQAAAAdXBzdHJlYW0gZml4dHVyZUlORFgT"
    "AAAAXQAAAQAAAG42SB/9ZulsuNTDK/gN1w4AVkVSVBQAAABdAAABAAAAaA5Fz+tgUUE8sPgFQNME"
    "lasATk9STSYAAABdAAABAAAAYP18EBgQlEbb1bMabIfSWEyLvzUUkO9/iywnknPnahAsSaoAVEVY"
    "QwMAAAB1djAHAAAAdGV4LnBuZxoAAABdAAABAAAAEMHU4Osl0T8lP7Edhj0WKjvYkRetLwAAQVRU"
    "UgUAAABjb2xvclYAAABdAAABAABfr4OF3Td6eFYIgx5+YwvlU6uOI4X+ueswqT4WcYmGBfhw8fVk"
    "1aMzD2iGR8v6dAd9Yd22by974fo0NzcXmzIohkx2SOsj5MsNG1xlcRHPM8p9emiA"
)
UPSTREAM_MG2 = (
    "T0NUTQUAAABNRzIABgAAAAUAAAABAAAAAQAAAAEAAAAQAAAAdXBzdHJlYW0gZml4dHVyZU1HMkgA"
    "AIA6AACAOwAAAAAAAAAAAAAAAAAAgD8AAIA/AACAPwMAAAADAAAAAwAAAFZFUlQWAAAAXQAAAQAA"
    "AG4iSPwR0jiR1RoycqQBmSvq9oaZR0lEWA0AAABdAAABAAAAZtpolMElKGaOgQBJTkRYEgAAAF0A"
    "AAEAAABuNkgf/PkC6Dnooysd43MATk9STRkAAABdAAABAAAAbiBJS10DobKvKrWkSspuKKLyASVC"
    "AABURVhDAwAAAHV2MAcAAAB0ZXgucG5nAACAORkAAABdAAABAAAAbgpn3wiOfkux0lqfHwzfFFqe"
    "itriiABBVFRSBQAAAGNvbG9yAACAOyMAAABdAAABAAAAbjhI5/o+DIdqsLb7s1oGzfOsatVrjM3e"
    "wRUJQRrHrFkA"
)

VERTICES = np.array(
    [[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1]],
    dtype=np.float32,
)
TRIANGLES = np.array(
    [[2, 0, 1], [0, 3, 1], [1, 4, 2], [3, 5, 1], [4, 4, 4]],
    dtype=np.uint32,
)
NORMALS = np.array(
    [
        [0, 0, 1],
        [0, -0.70710677, 0.70710677],
        [0.57735026, 0.57735026, 0.57735026],
        [1, 0, 0],
        [0, 0, 0],
        [-1, 0, 0],
    ],
    dtype=np.float32,
)
UV = np.array([[0, 0], [1, 0], [0, 1], [-0.25, 0.5], [1, 1], [2, -1]], dtype=np.float32)
ATTR = np.arange(24, dtype=np.float32).reshape(6, 4) / 7 - 1


def numpy_rearrange_and_deltas(indices):
    result = indices.copy()
    for triangle in result:
        if triangle[1] < triangle[0] and triangle[1] < triangle[2]:
            triangle[:] = triangle[[1, 2, 0]]
        elif triangle[2] < triangle[0] and triangle[2] < triangle[1]:
            triangle[:] = triangle[[2, 0, 1]]
    result = result[np.lexsort((result[:, 1], result[:, 0]))]
    delta = result.copy()
    with np.errstate(over="ignore"):
        for i in range(len(delta) - 1, -1, -1):
            delta[i, 1] -= delta[i - 1, 1] if i and delta[i, 0] == delta[i - 1, 0] else delta[i, 0]
            delta[i, 2] -= delta[i, 0]
            if i:
                delta[i, 0] -= delta[i - 1, 0]
    return result, delta


def test_mg1_decodes_upstream_fixture_exactly():
    mesh = ctm.loads(base64.b64decode(UPSTREAM_MG1))
    expected_triangles, _ = numpy_rearrange_and_deltas(TRIANGLES)
    assert mesh.method == "MG1"
    assert mesh.comment == "upstream fixture"
    assert np.array_equal(mesh.vertices, VERTICES)
    assert np.array_equal(mesh.triangles, expected_triangles)
    assert np.array_equal(mesh.normals, NORMALS)
    assert np.array_equal(mesh.uv_maps[0].values, UV)
    assert np.array_equal(mesh.attributes[0].values, ATTR)
    assert mesh.uv_maps[0].name == "uv0"
    assert mesh.uv_maps[0].file_name == "tex.png"


def test_mg2_decodes_upstream_fixture_with_upstream_quantization():
    mesh = ctm.loads(base64.b64decode(UPSTREAM_MG2))
    expected_vertices = np.array(
        [
            [0, 0, 0],
            [0.9996745, 0, 0],
            [0, 0.9996745, 0],
            [0.9996745, 0.9996745, 0],
            [0, 0, 0.9996745],
            [0.9996745, 0, 0.9996745],
        ],
        dtype=np.float32,
    )
    assert mesh.method == "MG2"
    assert np.array_equal(mesh.vertices, expected_vertices)
    assert np.array_equal(
        mesh.triangles,
        np.array([[0, 1, 2], [0, 4, 1], [1, 3, 2], [1, 4, 5], [3, 3, 3]], dtype=np.uint32),
    )
    assert np.allclose(
        mesh.normals,
        np.array([
            [0.016019063, 0.00012834149, 0.9998716],
            [-0.0018873691, -0.7071056, 0.70710546],
            [0.566361, 0.58964413, 0.57580817],
            [0, -1, -4.371139e-8],
            [0.99999994, -4.371139e-8, -1.2688051e-8],
            [-0.99999994, -4.371139e-8, 1.2688051e-8],
        ], dtype=np.float32),
        atol=2e-7,
        rtol=0,
    )
    assert np.array_equal(mesh.uv_maps[0].values, UV[[0, 1, 2, 4, 3, 5]])
    assert mesh.attributes[0].values == pytest.approx(ATTR[[0, 1, 2, 4, 3, 5]], abs=1 / 256)


def test_index_prediction_matches_direct_upstream_port_and_inverts():
    rng = np.random.default_rng(7)
    indices = rng.integers(0, 400, size=(500, 3), dtype=np.uint32)
    expected, expected_delta = numpy_rearrange_and_deltas(indices)
    arranged = _sorted_triangles(indices)
    deltas = _index_deltas(arranged)
    assert np.array_equal(arranged, expected)
    assert np.array_equal(deltas.view(np.uint32), expected_delta)
    restored = deltas.view(np.uint32).copy()
    lib().ctm_restore_indices(addr(restored), len(restored))
    assert np.array_equal(restored, expected)


@pytest.mark.parametrize("triangle_count", [1, 2, 4, 5, 8, 9, 131_072, 131_073])
def test_index_prediction_simd_tail_sizes(triangle_count):
    rng = np.random.default_rng(triangle_count)
    indices = rng.integers(0, 100, size=(triangle_count, 3), dtype=np.uint32)
    expected, expected_delta = numpy_rearrange_and_deltas(indices)
    arranged = _sorted_triangles(indices)
    deltas = np.empty_like(arranged)
    lib().ctm_make_index_deltas_to(addr(arranged), addr(deltas), len(arranged))
    assert np.array_equal(deltas.view(np.uint32), expected_delta)
    lib().ctm_restore_indices(addr(deltas), len(deltas))
    assert np.array_equal(deltas, expected)


@pytest.mark.parametrize("signed", [False, True])
def test_integer_byte_interleaving_matches_stream_c(signed):
    values = np.array(
        [[0, 1, -1], [2**31 - 1, -2**31, 0x12345678], [-17, 999, -1000]],
        dtype=np.int32,
    )
    transformed = values.copy()
    if signed:
        unsigned = transformed.view(np.uint32)
        unsigned[:] = np.where(transformed < 0, -1 - (transformed.astype(np.int64) << 1), transformed.astype(np.int64) << 1)
    expected = transformed.view(np.uint8).reshape(-1, 4)[:, ::-1].reshape(3, 3, 4)
    expected = expected.transpose(2, 1, 0).reshape(-1)
    packed = np.empty(values.size * 4, dtype=np.uint8)
    lib().ctm_interleave_ints(addr(values), addr(packed), 3, 3, signed)
    assert np.array_equal(packed, expected)
    restored = np.empty_like(values)
    lib().ctm_deinterleave_ints(addr(packed), addr(restored), 3, 3, signed)
    expected_restored = values.copy()
    if signed:
        # This is the upstream UInt32 wraparound at x == 0xffffffff.
        expected_restored[1, 1] = 0
    assert np.array_equal(restored, expected_restored)


@pytest.mark.parametrize(
    "count,signed",
    [(7, False), (131_071, False), (131_072, True)],
)
def test_integer_interleave_simd_tail_and_large_count(count, signed):
    rng = np.random.default_rng(count)
    values = rng.integers(-(2**30), 2**30, size=(count, 3), dtype=np.int32)
    transformed = values.copy()
    if signed:
        unsigned = transformed.view(np.uint32)
        unsigned[:] = np.where(
            transformed < 0,
            -1 - (transformed.astype(np.int64) << 1),
            transformed.astype(np.int64) << 1,
        )
    expected = (
        transformed.view(np.uint8)
        .reshape(count, 3, 4)[:, :, ::-1]
        .transpose(2, 1, 0)
        .reshape(-1)
    )
    packed = np.empty(values.size * 4, dtype=np.uint8)
    lib().ctm_interleave_ints(addr(values), addr(packed), count, 3, signed)
    assert np.array_equal(packed, expected)


def test_float_byte_interleaving_preserves_all_ieee_bits():
    bits = np.array([0, 0x80000000, 0x7F800000, 0xFF800000, 0x7FC01234, 0x3F800000], dtype=np.uint32)
    values = bits.view(np.float32).reshape(2, 3)
    packed = np.empty(values.size * 4, dtype=np.uint8)
    restored = np.empty_like(values)
    lib().ctm_interleave_floats(addr(values), addr(packed), 2, 3)
    lib().ctm_deinterleave_floats(addr(packed), addr(restored), 2, 3)
    assert np.array_equal(restored.view(np.uint32), bits.reshape(2, 3))


def test_grid_setup_matches_upstream_epsilon_and_resolution():
    minimum, maximum, division, size, indices = _grid(VERTICES)
    assert np.array_equal(minimum, [0, 0, 0])
    assert np.array_equal(maximum, [1, 1, 1])
    assert np.array_equal(division, [3, 3, 3])
    assert size == pytest.approx([1 / 3] * 3)
    assert np.array_equal(indices, [0, 2, 6, 18, 8, 20])

    collapsed = np.full((4, 3), 2.5, dtype=np.float32)
    minimum, maximum, division, size, indices = _grid(collapsed)
    assert np.array_equal(division, [4, 4, 4])
    assert np.array_equal(size, [0, 0, 0])
    assert np.array_equal(indices, [0, 0, 0, 0])


@pytest.mark.parametrize("method", ["MG1", "MG2"])
def test_roundtrip_normals_uv_attributes_and_comment(method):
    encoded = ctm.dumps(
        VERTICES,
        TRIANGLES,
        normals=NORMALS,
        uv_maps=[ctm.UVMap(UV, "uv0", "tex.png", 1 / 4096)],
        attributes=[ctm.AttributeMap(ATTR, "color", 1 / 256)],
        method=method,
        compression_level=1,
        comment="roundtrip",
    )
    mesh = ctm.loads(encoded)
    assert encoded[:4] == b"OCTM"
    assert mesh.comment == "roundtrip"
    assert len(mesh.vertices) == len(VERTICES)
    assert len(mesh.triangles) == len(TRIANGLES)
    if method == "MG1":
        assert np.array_equal(mesh.vertices, VERTICES)
        assert np.array_equal(mesh.normals, NORMALS)
        assert np.array_equal(mesh.uv_maps[0].values, UV)
        assert np.array_equal(mesh.attributes[0].values, ATTR)
    else:
        order = np.lexsort((VERTICES[:, 0], _grid(VERTICES)[4]))
        assert np.max(np.abs(mesh.vertices - VERTICES[order])) <= 1 / 1024
        assert np.linalg.norm(mesh.normals, axis=1) == pytest.approx(
            np.where(np.linalg.norm(mesh.normals, axis=1) > 0, 1, 0), abs=0.01
        )
        assert np.allclose(mesh.uv_maps[0].values, UV[order], atol=1 / 4096, rtol=0)


def test_single_triangle_and_unreferenced_vertex():
    vertices = np.vstack([VERTICES[:3], [9, 9, 9]]).astype(np.float32)
    mesh = ctm.loads(ctm.dumps(vertices, [[0, 1, 2]], method="MG2"))
    assert mesh.triangles.shape == (1, 3)
    assert mesh.vertices.shape == (4, 3)
    assert np.min(np.linalg.norm(mesh.vertices - [9, 9, 9], axis=1)) < 0.002


def test_duplicate_vertices_and_zero_area_faces():
    vertices = np.array([[0, 0, 0], [1, 0, 0], [1, 0, 0], [0, 1, 0]], dtype=np.float32)
    triangles = np.array([[0, 1, 2], [0, 2, 3]], dtype=np.uint32)
    for method in ("MG1", "MG2"):
        mesh = ctm.loads(ctm.dumps(vertices, triangles, method=method))
        assert len(mesh.triangles) == 2
        assert np.count_nonzero(np.all(mesh.vertices[:, None] == mesh.vertices[None, :], axis=2)) > len(vertices)


def test_non_manifold_edge_is_preserved():
    vertices = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1]], dtype=np.float32)
    triangles = np.array([[0, 1, 2], [1, 0, 3], [0, 1, 4]], dtype=np.uint32)
    mesh = ctm.loads(ctm.dumps(vertices, triangles, method="MG2"))
    assert len(mesh.triangles) == 3
    edge_counts = {}
    for triangle in mesh.triangles:
        for a, b in ((triangle[0], triangle[1]), (triangle[1], triangle[2]), (triangle[2], triangle[0])):
            edge = tuple(sorted((int(a), int(b))))
            edge_counts[edge] = edge_counts.get(edge, 0) + 1
    assert max(edge_counts.values()) == 3


@pytest.mark.parametrize(
    "vertices,triangles,message",
    [
        (np.empty((0, 3)), np.empty((0, 3), dtype=np.uint32), "at least one"),
        ([[0, 0, 0]], np.empty((0, 3), dtype=np.uint32), "at least one"),
        ([[np.nan, 0, 0]], [[0, 0, 0]], "finite"),
        ([[0, 0, 0]], [[0, 0, 1]], "outside"),
    ],
)
def test_invalid_meshes_are_rejected_like_openctm(vertices, triangles, message):
    with pytest.raises(ctm.CTMError, match=message):
        ctm.dumps(vertices, triangles)


def test_truncated_and_wrong_section_streams_are_rejected():
    encoded = ctm.dumps(VERTICES, TRIANGLES, method="MG1")
    with pytest.raises(ctm.CTMError, match="truncated"):
        ctm.loads(encoded[:-8])
    damaged = encoded.replace(b"INDX", b"NOPE", 1)
    with pytest.raises(ctm.CTMError, match="INDX"):
        ctm.loads(damaged)


def test_unsafe_input_narrowing_and_index_wrapping_are_rejected():
    with pytest.raises(ctm.CTMError, match="convert to float32"):
        ctm.dumps(VERTICES.astype(np.float64), TRIANGLES)
    with pytest.raises(ctm.CTMError, match="integer indices"):
        ctm.dumps(VERTICES, TRIANGLES.astype(np.float64))
    with pytest.raises(ctm.CTMError, match="fit in uint32"):
        ctm.dumps(VERTICES, [[0, 1, -1]])
    with pytest.raises(ctm.CTMError, match="fit in uint32"):
        ctm.dumps(VERTICES, np.array([[0, 1, 2**32]], dtype=np.uint64))
    with pytest.raises(ctm.CTMError, match="finite positive"):
        ctm.dumps(VERTICES, TRIANGLES, vertex_precision=np.nan)
    with pytest.raises(ctm.CTMError, match="finite positive"):
        ctm.dumps(
            VERTICES,
            TRIANGLES,
            uv_maps=[ctm.UVMap(UV, precision=1e-100)],
        )


def test_ffi_address_rejects_wrong_layout_dtype_and_empty_buffers():
    with pytest.raises(ValueError, match="C-contiguous"):
        addr(np.ones((3, 3), dtype=np.float32)[:, ::2])
    with pytest.raises(TypeError, match="float32"):
        addr(np.ones(3, dtype=np.float64))
    with pytest.raises(ValueError, match="empty"):
        addr(np.empty(0, dtype=np.uint8))


def test_hostile_header_counts_flags_and_trailing_data_are_rejected():
    encoded = bytearray(ctm.dumps(VERTICES, TRIANGLES, method="MG1"))
    huge = encoded.copy()
    huge[12:16] = (2**32 - 1).to_bytes(4, "little")
    with pytest.raises(ctm.CTMError, match="too large"):
        ctm.loads(huge)
    bad_flags = encoded.copy()
    bad_flags[28:32] = (2).to_bytes(4, "little")
    with pytest.raises(ctm.CTMError, match="flags"):
        ctm.loads(bad_flags)
    with pytest.raises(ctm.CTMError, match="trailing"):
        ctm.loads(encoded + b"x")


def test_file_api_and_multiple_named_maps(tmp_path):
    path = tmp_path / "mesh.ctm"
    ctm.save(
        path,
        VERTICES,
        TRIANGLES,
        uv_maps={"first": UV, "second": UV + np.float32(0.25)},
        attributes={"color": ATTR, "other": ATTR + np.float32(1)},
        method="MG1",
    )
    mesh = ctm.load(path)
    assert [item.name for item in mesh.uv_maps] == ["first", "second"]
    assert [item.name for item in mesh.attributes] == ["color", "other"]
    assert np.array_equal(mesh.uv_maps[1].values, UV + np.float32(0.25))
    assert np.array_equal(mesh.attributes[1].values, ATTR + np.float32(1))
